include ../../Makefile.Local
include ../../Makefile.Rules

INCLUDE = $(DUNEINC) $(UGINC) $(BOOSTINC) $(AMIRAINC) $(KASKADEINC) $(ITSOLINC) $(HYPREINC) $(TAUCSINC) $(TRILINOSINC) $(UMFPACKINC) $(ALUGRIDINC)
ifneq (,$(findstring -O1,$(OPTLOWFLAGS)))
FLAGS = $(WFLAGS) $(OPTLOWFLAGS)
else 
FLAGS = $(WFLAGS) $(OPTFLAGS) 
endif

statHeatTransfer: statHeatTransfer.o Makefile $(KASKADE7)/libs/libkaskade.a 
	$(CXX) $(FLAGS) $< $(KASKADE7)/libs/umfpack_solve.o $(KASKADE7)/libs/mumps_solve.o \
	$(KASKADE7)/libs/superlu_solve.o $(KASKADELIB) \
 $(DUNELIB) \
 $(UGLIB) \
 $(ALUGRIDLIB) \
 $(BOOSTLIB) \
 $(UMFPACKLIB) \
 $(MUMPSLIB) \
 $(ITSOLLIB) \
 $(HYPRELIB) \
 $(TAUCSLIB) \
 $(TRILINOSLIB) \
 $(PARDISOLIB) \
 $(AMIRALIB) \
 $(BLASLIB) $(FTNLIB) $(NUMALIB) -o $@


clean:
	rm -f gccerr.txt statHeatTransfer statHeatTransfer.o temperature.vtu *.bak run-*.json

depend:
	cp Makefile.gen Makefile; ../../gccmakedep -f Makefile $(INCLUDE) $(MAKEDEPENDFLAGS)  statHeatTransfer.cpp; ../../remove_install_deps Makefile

# DO NOT DELETE

