include ../../Makefile.Local
include ../../Makefile.Rules

INCLUDE = $(DUNEINC) $(UGINC) $(BOOSTINC) $(AMIRAINC) $(KASKADEINC) $(ITSOLINC) $(HYPREINC) $(TAUCSINC) $(UMFPACKINC) $(MUMPSINC)
FLAGS = $(WFLAGS) $(OPTFLAGS)
#FLAGS = $(WFLAGS) $(DEBUGFLAGS)


poisson: poisson.o Makefile $(KASKADE7)/libs/libkaskade.a 
	$(CXX) $< $(KASKADE7)/libs/umfpack_solve.o $(KASKADE7)/libs/mumps_solve.o \
	$(KASKADE7)/libs/superlu_solve.o $(KASKADELIB) \
 $(DUNELIB) \
 $(UGLIB) \
 $(BOOSTLIB) \
 $(UMFPACKLIB) \
 $(MUMPSLIB) \
 $(ITSOLLIB) \
 $(HYPRELIB) \
 $(TAUCSLIB) \
 $(PARDISOLIB) \
 $(AMIRALIB) \
 $(BLASLIB) $(FTNLIB) $(NUMALIB) -o $@

clean:
	rm -f gccerr.txt poisson poisson.o temperature.vtu *.bak run-*.json

depend:
	cp Makefile.gen Makefile; ../../gccmakedep -f Makefile $(INCLUDE) $(MAKEDEPENDFLAGS)  poisson.cpp; ../../remove_install_deps Makefile

# DO NOT DELETE

