include ../../Makefile.Local
include ../../Makefile.Rules

INCLUDE = $(DUNEINC) $(UGINC) $(BOOSTINC) $(AMIRAINC) $(KASKADEINC) $(ITSOLINC) $(HYPREINC) $(TAUCSINC) $(TRILINOSINC) $(UMFPACKINC) $(ALUGRIDINC)
FLAGS = $(WFLAGS) $(OPTFLAGS)

hbPrec: hbPrec.o Makefile $(KASKADE7)/libs/libkaskade.a 
	$(CXX) $(FLAGS) $< $(KASKADE7)/libs/umfpack_solve.o $(KASKADE7)/libs/mumps_solve.o \
	$(KASKADE7)/libs/superlu_solve.o $(KASKADELIB) \
 $(DUNELIB) \
 $(UGLIB) \
 $(ALUGRIDLIB) \
 $(BOOSTLIB) \
 $(UMFPACKLIB) \
 $(MUMPSLIB) \
 $(ITSOLLIB) \
 $(HYPRELIB) \
 $(TAUCSLIB) \
 $(TRILINOSLIB) \
 $(PARDISOLIB) \
 $(AMIRALIB) \
 $(BLASLIB) $(FTNLIB) $(NUMALIB) -o $@


clean:
	rm -f gccerr.txt hbPrec hbPrec.o temperature.vtu *.bak run-*.json

depend:
	cp Makefile.gen Makefile; ../../gccmakedep -f Makefile $(INCLUDE) $(MAKEDEPENDFLAGS)  hbPrec.cpp; ../../remove_install_deps Makefile

# DO NOT DELETE

